import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

/**
 * Geist Sans font configuration
 * Modern sans-serif font with variable weight support
 */
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

/**
 * Geist Mono font configuration  
 * Monospace font for code and technical content
 */
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/**
 * Metadata configuration for the application
 */
export const metadata: Metadata = {
  title: "Soma Technical",
  description: "Generated by create next app",
};

/**
 * RootLayout component defines the base HTML structure for the entire application
 * Sets up fonts, global styles, and provides the root container for all pages
 * 
 * @param children - The page content to render within the layout
 * @returns The root HTML structure with fonts and styling applied
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
